airflow:
  executor: LocalExecutor
  username: admin
  password: admin
  dags:
    gitSync:
      enabled: true
      repo: https://github.com/low-jos-code/airflow-repo.git
      branch: main
      revision: HEAD
      syncWait: 60
      depth: 1
  web:
    port: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: airflowpass

redis:
  enabled: true
