apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/low-jos-code/gitops-manifests.git'
    targetRevision: main
    path: airflow # The directory containing Chart.yaml/values.yaml

    helm:
      releaseName: "airflow"
      # If the subchart approach doesn't require nesting, remove 'releaseName' or tweak as needed
      valueFiles:
      - values.yaml # use our local overrides
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc

  revisionHistoryLimit: 5
  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true
  #   automated:
  #     selfHeal: true
  #   retry:
  #   limit: 3
  #   backoff:
  #     duration: 5s
  #     factor: 2
  #     maxDuration: 3m
