# infra-repo/airflow/values.yaml

# Since the official chart is a dependency (named "airflow"), we place all overrides
# under the "airflow" key if we want to override the subchart's values.

airflow:
  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.5.1 # or newer stable versio

  # Example: enable Git Sync to pull your DAGs from a separate repo
  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/low-jos-code/airflow-repo.git"
      branch: "main"
      subPath: "dags" # if your DAG files are under a "dags/" folder in that repo
      # Example: scale out some components

