apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: airflow
    targetRevision: 21.4.0

    helm:
      valuesObject:
        airflow:
          executor: LocalExecutor
          username: admin
          password: admin
          dags:
            gitSync:
              enabled: true
              repo: https://github.com/low-jos-code/airflow-repo.git
              branch: main
              revision: HEAD
              syncWait: 60
              depth: 1

          web:
            port: 8080

        postgresql:
          enabled: true
          auth:
            postgresPassword: airflowpass

        redis:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
