apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: airflow
    targetRevision: 22.7.1 # ✅ VALID chart version
    helm:
      values: |
        executor: LocalExecutor
        airflow:
          username: admin
          password: admin
        postgresql:
          enabled: true
          auth:
            postgresPassword: airflowpass
        redis:
          enabled: true
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/low-jos-code/airflow-repo.git
            branch: main
            subPath: dags
            depth: 1
            syncWait: 10
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
