apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/low-jos-code/gitops-manifests
    targetRevision: HEAD
    path: . # or "apps" depending on your structure
    helm:
      chart: airflow
      repoURL: https://airflow.apache.org
      version: 1.12.0
      valueFiles:
      - values/airflow-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
